In [610]:
import numpy as np

## Q#1: Create x array with elements equal to 1.

In [611]:
# write your code here ^_^
x = np.ones(5)

## Q#2: Create y array with elements equal to 0.

In [612]:
# write your code here ^_^
y = np.zeros(5)

## Q#3: Add x and y arrays.

In [613]:
# write your code here ^_^
xy = x + y

## Q#4: Print x array characteristics (e.g: dimension, shape, size, type).

In [614]:
# write your code here ^_^
print(x.shape, x.ndim, x.dtype, x.size)

(5,) 1 float64 5


## Q#5: Create a 2D array "called w" as the following:

|       |          |
| ----- | -------- |
| 11    | 12       |
| 13    | 14       |
| 15    | 16       |


In [615]:
# write your code here ^_^
w = np.array([[11, 12],
                 [13, 14],
                 [15, 16]])

## Q#6: Create z array contains the numbers from 1 to 3.

In [616]:
# write your code here ^_^
z = np.arange(1,4)

## Q#7: Combine the arrays z and w in horizontal way then save it in a new variable "newArray".

In [617]:
# write your code here ^_^
newArray = np.hstack((z[:, np.newaxis], w))
print(newArray)

[[ 1 11 12]
 [ 2 13 14]
 [ 3 15 16]]


## Q#8: Print all elements of "newArray" using the loop.

In [618]:
# write your code here ^_^
for i in newArray:
    for j in i:
        print(j)


1
11
12
2
13
14
3
15
16


## Q#9: Reverse the columns and rows of "newArray".

In [619]:
# write your code here ^_^
newArray = newArray[::-1, ::-1]

## Q#10: Decrement all elements of "newArray" with 1.

In [620]:
# write your code here ^_^
newArray = newArray - 1

## Q#11: Find smallest and biggest values in "newArray".

In [621]:
# write your code here ^_^
smallest = np.min(newArray)
biggest = np.max(newArray)


## Q#12: Print the first row of "newArray" using indexing.

In [622]:
# write your code here ^_^
print(newArray[0], newArray[-1])

[15 14  2] [11 10  0]


## Q#13: Print the number equals 12 of "newArray" using indexing.

In [623]:
index = np.where(newArray == 12)
x = index[0][0]
y = index[1][0]
print(newArray[x, y])


12


## Q#14: Print the numbers equal 0 and 13 of "newArray" using indexing.

In [624]:
# write your code here ^_^
# Define the values to search for
values_to_find = [0, 13]

# Iterate over each value and find its location in newArray
for value in values_to_find:
    if value in newArray:
        indices = np.where(newArray == value)
        for x, y in zip(indices[0], indices[1]):
            print(newArray[x,y])


0
13


## Q#15: Change the shape of "newArray" to (9,1).

In [625]:
# write your code here ^_^
newArray = newArray.reshape(9,1)

## Q#16: Change the shape of "newArray" to (3,3).

In [626]:
# write your code here ^_^
newArray = newArray.reshape(3,3)
print(newArray)


[[15 14  2]
 [13 12  1]
 [11 10  0]]


# Well Done 🎉