In [3]:
import numpy as np

## Q#1: Create x array with elements equal to 1.

In [4]:
# write your code here ^_^
x = np.ones(5)
print(x)

[1. 1. 1. 1. 1.]


## Q#2: Create y array with elements equal to 0.

In [5]:
# write your code here ^_^
y = np.zeros(5)
print(y)

[0. 0. 0. 0. 0.]


## Q#3: Add x and y arrays.

In [6]:
# write your code here ^_^
sumArr = x + y
print(sumArr)

[1. 1. 1. 1. 1.]


## Q#4: Print x array characteristics (e.g: dimension, shape, size, type).

In [7]:
# write your code here ^_^
print("array x dimension:", x.ndim)
print("array x shape:", x.shape)
print("array x size:", x.size)
#I am not sure which one you want so printed both of them 
print("array x type:", x.dtype)
print("array x type:", type(x))


array x dimension: 1
array x shape: (5,)
array x size: 5
array x type: float64
array x type: <class 'numpy.ndarray'>


## Q#5: Create a 2D array "called w" as the following:

|       |          |
| ----- | -------- |
| 11    | 12       |
| 13    | 14       |
| 15    | 16       |


In [8]:
# write your code here ^_^
w = np.array([[11, 12], [13, 14],[15, 16]])
print(w)


[[11 12]
 [13 14]
 [15 16]]


## Q#6: Create z array contains the numbers from 1 to 3.

In [9]:
# write your code here ^_^
z = np.linspace(1,3, 3)
print(z)

# or you can simpally do this 
z = np.array([1,2,3])
print(z)

[1. 2. 3.]
[1 2 3]


## Q#7: Combine the arrays z and w in horizontal way then save it in a new variable "newArray".

In [10]:
# write your code here ^_^
z = z.reshape(-1, 1)

newArray = np.hstack((z, w))
newArray


array([[ 1, 11, 12],
       [ 2, 13, 14],
       [ 3, 15, 16]])

## Q#8: Print all elements of "newArray" using the loop.

In [11]:
# write your code here ^_^
for n in newArray.flat:
    print(n)

1
11
12
2
13
14
3
15
16


## Q#9: Reverse the columns and rows of "newArray".

In [12]:
# write your code here ^_^
newArray = newArray.T
print(newArray)

[[ 1  2  3]
 [11 13 15]
 [12 14 16]]


## Q#10: Decrement all elements of "newArray" with 1.

In [13]:
# write your code here ^_^
newArray -= 1
newArray 

array([[ 0,  1,  2],
       [10, 12, 14],
       [11, 13, 15]])

## Q#11: Find smallest and biggest values in "newArray".

In [14]:
# write your code here ^_^
print("Smallest value:", np.min(newArray))
print("Biggest value:", np.max(newArray))

Smallest value: 0
Biggest value: 15


## Q#12: Print the first row of "newArray" using indexing.

In [15]:
# write your code here ^_^
print(newArray[0])

[0 1 2]


## Q#13: Print the number equals 12 of "newArray" using indexing.

In [16]:
# write your code here ^_^
print(newArray[1][1])

12


## Q#14: Print the numbers equal 0 and 13 of "newArray" using indexing.

In [17]:
# write your code here ^_^
print(newArray[0][0])
print(newArray[2][1])

0
13


## Q#15: Change the shape of "newArray" to (9,1).

In [18]:
# write your code here ^_^
newArray = newArray.reshape(9, 1)
print(newArray)

[[ 0]
 [ 1]
 [ 2]
 [10]
 [12]
 [14]
 [11]
 [13]
 [15]]


## Q#16: Change the shape of "newArray" to (3,2).

In [19]:
# write your code here ^_^
print(newArray.reshape(3, 3))

[[ 0  1  2]
 [10 12 14]
 [11 13 15]]


# Well Done 🎉