# Q1: Import numpy library

In [2]:
import numpy as np

# Q2: Generate a sequence of 15 floats using linspace() function

In [11]:
# here we generate sequence of 15 floats.
# to set the start we use "start" parameter, here we start at 1
# to set the last number we use "stop" parameter, here we end at 15
# to set the number of elements to generate we use "num" parameter, here have 15
seq= np.linspace(start=0,stop=1, num=15)
print(seq)

[0.         0.07142857 0.14285714 0.21428571 0.28571429 0.35714286
 0.42857143 0.5        0.57142857 0.64285714 0.71428571 0.78571429
 0.85714286 0.92857143 1.        ]


# Q3: Create a 3-D array in shape (2, 2, 3) containing the four arrays given below 
Note : the array's name is up to you.

|      |       |          |         |
|------| ----- | -------- | ------- |
|arr1 | 1.1    | 2.1       | 3.1        |
|arr2 | 4.1    | 5.1       | 6.1        |
|arr3 | 7.1    | 8.1       | 9.1        |
|arr4 | 10.1   | 11.1      | 12.1       |

In [72]:
# step-1: create the array's
a1 = np.array([1.1, 2.1, 3.1])
a2 = np.array([4.1, 5.1, 6.1])
a3 = np.array([7.1, 8.1, 9.1])
a4 = np.array([10.1, 11.1, 12.1])

# step-2: now we need to merge the arrays to reshape them this can be achived by different ways, here i will use vstack
arr3d = np.vstack([a1,a2,a3,a4]) # now we have a (4,3) array
print(f"our 3d-array (matrix): \n{arr3d}\n\n shape: {arr3d.shape}")

# step-3: now we want to reshape it to fit our shape (2,2,3), to do this we can use np.reshape()
arr3d = arr3d.reshape((2,2,3))
print(f"\n\nour 3d-array (matrix): \n{arr3d}\n\n shape: {arr3d.shape}")

our 3d-array (matrix): 
[[ 1.1  2.1  3.1]
 [ 4.1  5.1  6.1]
 [ 7.1  8.1  9.1]
 [10.1 11.1 12.1]]

 shape: (4, 3)


our 3d-array (matrix): 
[[[ 1.1  2.1  3.1]
  [ 4.1  5.1  6.1]]

 [[ 7.1  8.1  9.1]
  [10.1 11.1 12.1]]]

 shape: (2, 2, 3)


# Q4: Print the following:
Note: use the same array from Q3.
- Array's type.
- Array's elements datatype.
- Array's shape.
- Array's size.
- Array's dimention.

In [77]:
# here we will print the details of our 3d-array
print(f"our 3d-array (array of matrices): \n{arr3d}")
print("")
print(f"Array's type: {type(arr3d)}")
print(f"Array's elements datatype: {arr3d.dtype}")
print(f"Array's shape: {arr3d.shape}")
print(f"Array's size: {arr3d.size}")
print(f"Array's dimention: {arr3d.ndim}")

our 3d-array (array of matrices): 
[[[ 1.1  2.1  3.1]
  [ 4.1  5.1  6.1]]

 [[ 7.1  8.1  9.1]
  [10.1 11.1 12.1]]]

Array's type: <class 'numpy.ndarray'>
Array's elements datatype: float64
Array's shape: (2, 2, 3)
Array's size: 12
Array's dimention: 3


# Q5:  Change the array dimention from 3-D to 4-D
Note: use the same array from Q3.
- Create a new array to hold the changes. 
- Print the new array's dimention and shape.

In [78]:
# this is our old 3d-array we want to reshape it to be a 4d array
print(f"our 3d-array (array of matrices): \n{arr3d}\n\n number of dimensions: {arr3d.ndim}\n shape: {arr3d.shape}")

'''
To solve this question we need to consider the 4d-array as a matrix of matrices, where each element is a 3-D array.
The shape of the 4d-array should be such that multiplying its dimensions gives the total number of elements.
Example, with 4 arrays of 3 elements each (totaling 12 elements), 
possible shapes are:
    [
        (1, 1, 2, 6),
        (1, 2, 2, 3), 
        (2, 1, 1, 6),
        (2, 2, 1, 3)
    ]
'''
# here i went with 2,2,1,3
arr4d = arr3d.reshape((2,2,1,3))
print(f"\n\nour 4d-array (matrix of matrices): \n{arr4d}\n\n number of dimensions: {arr4d.ndim}\n shape: {arr4d.shape}")

our 3d-array (array of matrices): 
[[[ 1.1  2.1  3.1]
  [ 4.1  5.1  6.1]]

 [[ 7.1  8.1  9.1]
  [10.1 11.1 12.1]]]

 number of dimensions: 3
 shape: (2, 2, 3)


our 4d-array (matrix of matrices): 
[[[[ 1.1  2.1  3.1]]

  [[ 4.1  5.1  6.1]]]


 [[[ 7.1  8.1  9.1]]

  [[10.1 11.1 12.1]]]]

 number of dimensions: 4
 shape: (2, 2, 1, 3)


# Q6: Change the array's elements datatype to integer  
Note: use the same array from Q5.

- Create a new array to hold the changes. 
- Print the new array.

In [86]:
# this can be solved by may ways but here i will use astype()
arr4dInt =arr4d.astype(int)

print(f"\n\nour 4d-array (matrix of matrices): \n{arr4dInt}\n\n number of dimensions: {arr4dInt.ndim}\n dtype: {arr4dInt.dtype}")



our 4d-array (matrix of matrices): 
[[[[ 1  2  3]]

  [[ 4  5  6]]]


 [[[ 7  8  9]]

  [[10 11 12]]]]

 number of dimensions: 4
 dtype: int32


# Q7: Print all array's elements using for loop
Note: use the same array from Q6.

Hint: use nditer()

In [95]:
# np.nditer(arr4dInt) will return iterable object, this object can be used traverse the elements of our arr4dInt
print(f"The output of np.nditer(arr4dInt): {list(np.nditer(arr4dInt))}\n")

print("Loop Result:")
# this is how to traverse the elements of an array no matter its dimensions
for element in np.nditer(arr4dInt):
    print(element)

The output of np.nditer(arr4dInt): [array(1), array(2), array(3), array(4), array(5), array(6), array(7), array(8), array(9), array(10), array(11), array(12)]

Loop Result:
1
2
3
4
5
6
7
8
9
10
11
12


# Q8:  Print number 8 using array slicing
Note: use the same array from Q6.

In [102]:
''' 
    # First index : 1
    [
        # Second index
        [
            # Third Index
            [
                #Fourth Index
                [ 1,  2,  3]
            ],
            [
                #Fourth Index
                [ 4,  5,  6]
            ]
        ],

        # Second index: 0
        [
            # Third Index: 0
            [
                #Fourth Index: 1
                [ 7,  8,  9]
            ],
            [
                [10, 11, 12]
            ]
        ]
    ]
        '''

# to print number 8 we can refer to the comment above to traverse the array using slicing or indexing
print(arr4dInt[1][0][0][1])

8


# Q9: Print number 5 and number 6 using array slicing
Note: use the same array from Q6.

In [103]:
''' 
    # First index : 0
    [
        # Second index: 1
        [
            # Third Index: 0
            [
                #Fourth Index
                [ 1,  2,  3]
            ],
            [
                #Fourth Index: [1:3]
                [ 4,  5,  6]
            ]
        ],

        # Second index
        [
            # Third Index
            [
                #Fourth Index
                [ 7,  8,  9]
            ],
            [
                [10, 11, 12]
            ]
        ]
    ]
        '''

# to print number 5 and 6 we can refer to the comment above to traverse the array using slicing or indexing
print(arr4dInt[0][1][0][1:3])

[5 6]


# Q10: Search for number 8 using where()
Note: use the same array from Q6.

Note: where() is only used with small data.

*the output represents the path of the index that leads to number 8*

In [117]:
# here we will use np.where() and pass "arr4dInt == 8", this will return the index where 8 is
index = np.where(arr4dInt == 8)
print(f"the index is:{[int(i) for i in index]} \noutput is: {arr4dInt[index]}")

the index is:[1, 0, 0, 1]
output is: [8]


# Q11: Reshape the array as the following

    array([[[ 1, 2],
            [ 3,  4],
            [ 5,  6]],

           [[ 7,  8],
            [ 9, 10],
            [11, 12]]])
            
 Note: use the same array from Q6.

In [125]:
# to solve this issue we count the shape or use .shape for this array
temp = np.array([
    [[ 1, 2], [ 3,  4], [ 5,  6]],
    [[ 7,  8],[ 9, 10],[11, 12]]
    ])

print(f"Target shape: {temp.shape}")
arr4dInt3d = arr4dInt.reshape((2,3,2))
print(f"old array shape: {arr4dInt.shape} \nnew array shape: {arr4dInt3d.shape}\n new array: \n{arr4dInt3d}")

Target shape: (2, 3, 2)
old array shape: (2, 2, 1, 3) 
new array shape: (2, 3, 2)
 new array: 
[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


# Q12: Join the given arrays below 
    arr1 = np.array([['A', 'B'], ['E', 'F']])
    arr2 = np.array([['C', 'D'], ['G', 'H']])
## Q12.1: Join the arrays without specifying the axis 

In [193]:
arr1 = np.array([['A', 'B'], ['E', 'F']])
arr2 = np.array([['C', 'D'], ['G', 'H']])

joined_array = np.concatenate((arr1,arr2))
print(joined_array)

[['A' 'B']
 ['E' 'F']
 ['C' 'D']
 ['G' 'H']]


# Q12.2: Join the arrays along rows with axis = 1 

In [194]:
joined_array_1 = np.stack((arr1,arr2), axis=1)
print(joined_array_1)

[[['A' 'B']
  ['C' 'D']]

 [['E' 'F']
  ['G' 'H']]]


# Q13: Split the array into two arrays with axis = 1, each array should contain four arrays. 
Note: use the same array from Q12.1

In [243]:
# Step 1: Split the array into 2 arrays along axis 0
split_arrays = np.split(joined_array, 2, axis=0)


# Step 2: Split the arrays inside each array to have 4 arrays inside each
for i in range(len(split_arrays)):
    split_arrays[i] = np.split(split_arrays[i], 2, axis=1)

# cast it into np.array
split_arrays =  np.array(split_arrays)

print(f"Array 1: \n{split_arrays[0]}\n shape: {split_arrays[0].shape}\n")
print(f"Array 2: \n{split_arrays[1]}\n shape: {split_arrays[0].shape}")

Array 1: 
[[['A']
  ['E']]

 [['B']
  ['F']]]
 shape: (2, 2, 1)

Array 2: 
[[['C']
  ['G']]

 [['D']
  ['H']]]
 shape: (2, 2, 1)
