In [4]:
# Once we install the numpy :  pip install numpy -->  we import it 
import numpy as np

## Q#1: Create x array with elements equal to 1.

In [33]:
x = np.array([1])

print(x)

[1]


## Q#2: Create y array with elements equal to 0.

In [32]:
# write your code here ^_^

y = np.array([0])


print(y)


[0]


## Q#3: Add x and y arrays.

In [41]:
# write your code here ^_^

a = np.concatenate((x , y))

print(a)



[1 0]


## Q#4: Print x array characteristics (e.g: dimension, shape, size, type).

In [51]:
# write your code here ^_^

print("the dimension of x is: ", x.ndim)

print("the shape of x is: ", x.shape)

print("the size of x is: ", np.size(x))

print("the data type of x is: ", x.dtype)


the dimension of x is:  1
the shape of x is:  (1,)
the size of x is:  1
the data type of x is:  int32


## Q#5: Create a 2D array "called w" as the following:

|       |          |
| ----- | -------- |
| 11    | 12       |
| 13    | 14       |
| 15    | 16       |


In [132]:
# write your code here ^_^

w = np.array([[11,12],[13,14],[15,16]])

print(w)

[[11 12]
 [13 14]
 [15 16]]


## Q#6: Create z array contains the numbers from 1 to 3.

In [133]:
# write your code here ^_^

z = np.array([1, 2, 3])
print(z)

[1 2 3]


## Q#7: Combine the arrays z and w in horizontal way then save it in a new variable "newArray".

In [159]:
# write your code here ^_^

z = np.array([1,2,3])

w = np.array([[11,12], [13,14], [15,16]])


z_reshaped = np.reshape(z, (3,1))

newArray = np.concatenate((w, z_reshaped), axis=1)

print(newArray)

[[11 12  1]
 [13 14  2]
 [15 16  3]]


## Q#8: Print all elements of "newArray" using the loop.

In [160]:
# write your code here ^_^

for i in newArray:
    print(i)



[11 12  1]
[13 14  2]
[15 16  3]


## Q#9: Reverse the columns and rows of "newArray".

In [164]:
# write your code here ^_^

reverse_newArray = np.transpose(newArray)

print(reverse_newArray)

[[11 13 15]
 [12 14 16]
 [ 1  2  3]]


## Q#10: Decrement all elements of "newArray" with 1.

In [166]:
# write your code here ^_^

value_to_subtract = 1

decremented_array = newArray - value_to_subtract

print("original array is: ", newArray)
print("decremented_array is: ", decremented_array)

original array is:  [[11 12  1]
 [13 14  2]
 [15 16  3]]
decremented_array is:  [[10 11  0]
 [12 13  1]
 [14 15  2]]


## Q#11: Find smallest and biggest values in "newArray".

In [168]:
# write your code here ^_^

smallest_value = np.amin(newArray)

biggest_value = np.amax(newArray)

print("smallest value is: ", smallest_value)
print("biggest value is: ", biggest_value)

smallest value is:  1
biggest value is:  16


## Q#12: Print the first row of "newArray" using indexing.

In [172]:
# write your code here ^_^

print(newArray[0])


[11 12  1]


## Q#13: Print the number equals 12 of "newArray" using indexing.

In [183]:
# write your code here ^_^


print(newArray[0][1])



12


## Q#14: Print the numbers equal 1 and 13 of "newArray" using indexing.

In [201]:
# write your code here ^_^

print(newArray[1][0],newArray[0][2])



13 1


## Q#15: Change the shape of "newArray" to (9,1).

In [193]:
# write your code here ^_^

newArray_reshape = newArray.reshape(9,1)

print(newArray_reshape)

[[11]
 [12]
 [ 1]
 [13]
 [14]
 [ 2]
 [15]
 [16]
 [ 3]]


## Q#16: Change the shape of "newArray" to (3,3).

In [195]:
# write your code here ^_^

newArray_reshape = newArray.reshape(3,3)

print(newArray_reshape)

[[11 12  1]
 [13 14  2]
 [15 16  3]]


# Well Done 🎉