# Q1: Import numpy library

In [4]:
# write your code here ^_^
import numpy as np

# Q2: Generate a sequence of 15 floats using linspace() function

In [6]:
# write your code here ^_^
sequence = np.linspace(0.0 , 3.0, 15)
print(sequence)

[0.         0.21428571 0.42857143 0.64285714 0.85714286 1.07142857
 1.28571429 1.5        1.71428571 1.92857143 2.14285714 2.35714286
 2.57142857 2.78571429 3.        ]


# Q3: Create a 3-D array in shape (2, 2, 3) containing the four arrays given below 
Note : the array's name is up to you.

|      |       |          |         |
|------| ----- | -------- | ------- |
|arr1 | 1.1    | 2.1       | 3.1        |
|arr2 | 4.1    | 5.1       | 6.1        |
|arr3 | 7.1    | 8.1       | 9.1        |
|arr4 | 10.1   | 11.1      | 12.1       |

In [7]:
# write your code here ^_^
arr1 = np.array([1.1, 2.1, 3.1])
arr2 = np.array([4.1, 5.1, 6.1])
arr3 = np.array([7.1, 8.1, 9.1])
arr4 = np.array([10.1, 11.1, 12.1])

array3D = np.array([[arr1, arr2], [arr3, arr4]])
print(array3D)

[[[ 1.1  2.1  3.1]
  [ 4.1  5.1  6.1]]

 [[ 7.1  8.1  9.1]
  [10.1 11.1 12.1]]]


# Q4: Print the following:
Note: use the same array from Q3.
- Array's type.
- Array's elements datatype.
- Array's shape.
- Array's size.
- Array's dimention.

In [10]:
# write your code here ^_^
print("Array's type: ", type(array3D))
print("Array's datatype: ", array3D.dtype)
print("Array's shape: ", array3D.shape)
print("Array's size: ", array3D.size)
print("Array's dimension: ", array3D.ndim)

Array's type:  <class 'numpy.ndarray'>
Array's datatype:  float64
Array's shape:  (2, 2, 3)
Array's size:  12
Array's dimension:  3


# Q5:  Change the array dimention from 3-D to 4-D
Note: use the same array from Q3.
- Create a new array to hold the changes. 
- Print the new array's dimention and shape.

In [28]:
# write your code here ^_^

array4D = np.expand_dims(array3D, axis=0)
print("Array's dimension: ", array4D.ndim)
print("Array's shape: ", array4D.shape)

Array's dimension:  4
Array's shape:  (1, 2, 2, 3)


# Q6: Change the array's elements datatype to integer  
Note: use the same array from Q5.

- Create a new array to hold the changes. 
- Print the new array.

In [29]:
# write your code here ^_^
arrayInt=array4D.astype(int)
print(arrayInt)

[[[[ 1  2  3]
   [ 4  5  6]]

  [[ 7  8  9]
   [10 11 12]]]]


# Q7: Print all array's elements using for loop
Note: use the same array from Q6.

Hint: use nditer()

In [30]:
# write your code here ^_^
for i in np.nditer(arrayInt) : 
 print(i)

1
2
3
4
5
6
7
8
9
10
11
12


# Q8:  Print number 8 using array slicing
Note: use the same array from Q6.

In [62]:
# write your code here ^_^
num8 = arrayInt[0,1,0,1]
print(num8)

8


# Q9: Print number 5 and number 6 using array slicing
Note: use the same array from Q6.

In [64]:
# write your code here ^_^
num5_6 = arrayInt[0, 0, 1, 1:3]
print(num5_6)

[5 6]


# Q10: Search for number 8 using where()
Note: use the same array from Q6.

Note: where() is only used with small data.

*the output represents the path of the index that leads to number 8*

In [67]:
# write your code here ^_^
search8 = np.where(arrayInt == 8)
print(search8)


(array([0]), array([1]), array([0]), array([1]))


# Q11: Reshape the array as the following

    array([[[ 1, 2],
            [ 3,  4],
            [ 5,  6]],

           [[ 7,  8],
            [ 9, 10],
            [11, 12]]])
            
 Note: use the same array from Q6.

In [68]:
# write your code here ^_^
reshaped = arrayInt.reshape(2 ,3 ,2)
print(reshaped)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


# Q12: Join the given arrays below 
    arr1 = np.array([['A', 'B'], ['E', 'F']])
    arr2 = np.array([['C', 'D'], ['G', 'H']])
## Q12.1: Join the arrays without specifying the axis 

In [71]:
# write your code here ^_^
arr1 = np.array([['A', 'B'], ['E', 'F']])
arr2 = np.array([['C', 'D'], ['G', 'H']])
joineArr = np.concatenate((arr1, arr2))
print(joineArr)

[['A' 'B']
 ['E' 'F']
 ['C' 'D']
 ['G' 'H']]


# Q12.2: Join the arrays along rows with axis = 1 

In [72]:
# write your code here ^_^
joineArr = np.concatenate((arr1, arr2), axis=1)
print(joineArr)

[['A' 'B' 'C' 'D']
 ['E' 'F' 'G' 'H']]


# Q13: Split the array into two arrays with axis = 1, each array should contain four arrays. 
Note: use the same array from Q12.1

In [76]:
# write your code here ^_^
splitArray = np.split(joineArr, 2, axis= 1)
for s in splitArray:
    print(s)

[['A' 'B']
 ['E' 'F']]
[['C' 'D']
 ['G' 'H']]
