# Q1: Import numpy library

In [2]:
# write your code here ^_^

import numpy                       # Import the numpy module
import numpy as np                  # Import the numpy module and create an alias 'np' for it
from numpy import array, reshape   # Import the 'array' and 'reshape' functions from numpy
    



# Q2: Generate a sequence of 15 floats using linspace() function

In [19]:
# write your code here ^_^

sequence = np.linspace(10, 20, num = 15)        # the linspace function expected 3 params, 10 to 20 is the range of values "start and stop" and the 15 is the length "num" of the array

print(sequence)

[10.         10.35714286 10.71428571 11.07142857 11.42857143 11.78571429
 12.14285714 12.5        12.85714286 13.21428571 13.57142857 13.92857143
 14.28571429 14.64285714 15.        ]


# Q3: Create a 3-D array in shape (2, 2, 3) containing the four arrays given below 
Note : the array's name is up to you.

|      |       |          |         |
|------| ----- | -------- | ------- |
|arr1 | 1.1    | 2.1       | 3.1        |
|arr2 | 4.1    | 5.1       | 6.1        |
|arr3 | 7.1    | 8.1       | 9.1        |
|arr4 | 10.1   | 11.1      | 12.1       |

In [15]:
# write your code here ^_^

import numpy as np

arr1 = np.array([1.1, 2.1, 3.1])                # Create the arrays
arr2 = np.array([4.1, 5.1, 6.1])
arr3 = np.array([7.1, 8.1, 9.1])
arr4 = np.array([10.1, 11.1, 12.1])

newArray = np.array([arr1, arr2, arr3, arr4])     # Create the 3-D array

newArray = newArray.reshape(2, 2, 3)               # Reshape the 3-D array to the desired shape (2, 2, 3)

print(newArray)


[[[ 1.1  2.1  3.1]
  [ 4.1  5.1  6.1]]

 [[ 7.1  8.1  9.1]
  [10.1 11.1 12.1]]]


# Q4: Print the following:
Note: use the same array from Q3.
- Array's type.
- Array's elements datatype.
- Array's shape.
- Array's size.
- Array's dimention.

In [23]:
# write your code here ^_^


print("Array type is:", type(newArray))      # Print the array type

print("Array elements datatype are:", newArray.dtype)     # Print the array elements datatype

print("Array shape is:", newArray.shape)         # Print the array shape

print("Array size is:", newArray.size)           # Print the array size

print("Array dimension is :", newArray.ndim)      # Print the array dimensions

Array type is: <class 'numpy.ndarray'>
Array elements datatype are: float64
Array shape is: (2, 2, 3)
Array size is: 12
Array dimension is : 3


# Q5:  Change the array dimention from 3-D to 4-D
Note: use the same array from Q3.
- Create a new array to hold the changes. 
- Print the new array's dimention and shape.

In [33]:
# write your code here ^_^

array_4Dimentions = newArray.reshape(1, 2, 2, 3)            # Reshape the array to 4-D

print("New array's dimension:", array_4Dimentions.ndim)     # Print the new array's dimension and shape
print("New array's shape:", array_4Dimentions.shape)
print("The 4 Dimenations araay : \n", array_4Dimentions)    # we can see there is an extra square bracket which is represent the new dimension

New array's dimension: 4
New array's shape: (1, 2, 2, 3)
The 4 Dimenations araay : 
 [[[[ 1.1  2.1  3.1]
   [ 4.1  5.1  6.1]]

  [[ 7.1  8.1  9.1]
   [10.1 11.1 12.1]]]]


# Q6: Change the array's elements datatype to integer  
Note: use the same array from Q5.

- Create a new array to hold the changes. 
- Print the new array.

In [38]:
# write your code here ^_^

array_int = array_4Dimentions.astype(int)       # Change the array elements datatype to integer 

print(array_int)                       # Print the new array

[[[[ 1  2  3]
   [ 4  5  6]]

  [[ 7  8  9]
   [10 11 12]]]]


# Q7: Print all array's elements using for loop
Note: use the same array from Q6.

Hint: use nditer()

In [43]:
# write your code here ^_^

for element in np.nditer(array_int):
    print(element, end =' ')

1 2 3 4 5 6 7 8 9 10 11 12 

# Q8:  Print number 8 using array slicing
Note: use the same array from Q6.

In [64]:
# write your code here ^_^

# we can access any element in the array by following this technique:

print("By using only the first index:\n", array_int[0], "\n")
print("By using the two indexes:\n", array_int[0, 1], "\n")
print("By using the three indexes:\n", array_int[0, 1, 0], "\n")
print("By using the four indexes:\n", array_int[0, 1, 0, 1])        # by following this approach we will reach any element that we want


By using only the first index:
 [[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]] 

By using the two indexes:
 [[ 7  8  9]
 [10 11 12]] 

By using the three indexes:
 [7 8 9] 

By using the four indexes:
 8


# Q9: Print number 5 and number 6 using array slicing
Note: use the same array from Q6.

In [71]:
# write your code here ^_^

print("Accessing the number 5 :\n", array_int[0, 0, 1, 1]) 
print("Accessing the number 6 :\n", array_int[0, 0, 1, 2]) 


Accessing the number 5 :
 5
Accessing the number 6 :
 6


# Q10: Search for number 8 using where()
Note: use the same array from Q6.

Note: where() is only used with small data.

*the output represents the path of the index that leads to number 8*

In [75]:
# write your code here ^_^

index_of_8 = np.where(array_int == 8)

# Print the indices
print("index of number 8:", index_of_8)

index of number 8: (array([0], dtype=int64), array([1], dtype=int64), array([0], dtype=int64), array([1], dtype=int64))


# Q11: Reshape the array as the following

    array([[[ 1, 2],
            [ 3,  4],
            [ 5,  6]],

           [[ 7,  8],
            [ 9, 10],
            [11, 12]]])
            
 Note: use the same array from Q6.

In [76]:
# write your code here ^_^

reshaped_array = array_int.reshape(2, 3, 2)

print(reshaped_array)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


# Q12: Join the given arrays below 
    arr1 = np.array([['A', 'B'], ['E', 'F']])
    arr2 = np.array([['C', 'D'], ['G', 'H']])
## Q12.1: Join the arrays without specifying the axis 

In [77]:
# write your code here ^_^

import numpy as np

arr1 = np.array([['A', 'B'], ['E', 'F']])
arr2 = np.array([['C', 'D'], ['G', 'H']])

joined_array = np.concatenate((arr1, arr2))

print(joined_array)


[['A' 'B']
 ['E' 'F']
 ['C' 'D']
 ['G' 'H']]


# Q12.2: Join the arrays along rows with axis = 1 

In [78]:
# write your code here ^_^

joined_array = np.concatenate((arr1, arr2), axis=1)

print(joined_array)

[['A' 'B' 'C' 'D']
 ['E' 'F' 'G' 'H']]


# Q13: Split the array into two arrays with axis = 1, each array should contain four arrays. 
Note: use the same array from Q12.1

In [88]:
# write your code here ^_^

split_arrays = np.split(joined_array, 2, axis=1)

print("The first array : \n", split_arrays[0])
print("The second array : \n", split_arrays[1])




The first array : 
 [['A' 'B']
 ['E' 'F']]
The second array : 
 [['C' 'D']
 ['G' 'H']]
