In [92]:
import numpy as np

## Q#1: Create x array with elements equal to 1.

In [93]:
x = np.array([1])

## Q#2: Create y array with elements equal to 0.

In [94]:
y = np.array([])

## Q#3: Add x and y arrays.

In [95]:
x + y

array([], dtype=float64)

## Q#4: Print x array characteristics (e.g: dimension, shape, size, type).

In [96]:
print("array x's dimension ", x.ndim)
print("array x's shape ", x.shape)
print("array x's size ", x.size)
print("array x's type ", x.dtype)

array x's dimension  1
array x's shape  (1,)
array x's size  1
array x's type  int32


## Q#5: Create a 2D array "called w" as the following:

|       |          |
| ----- | -------- |
| 11    | 12       |
| 13    | 14       |
| 15    | 16       |


In [97]:
w = np.array([[11, 12], [13, 14],[15, 16]])
print(w)

[[11 12]
 [13 14]
 [15 16]]


## Q#6: Create z array contains the numbers from 1 to 3.

In [98]:
z = np.array([1, 2, 3])

## Q#7: Combine the arrays z and w in horizontal way then save it in a new variable "newArray".

In [99]:
# reshape
newZ = np.reshape(z, (len(z), 1))
newArray = np.concatenate((newZ, w), axis=1)

## Q#8: Print all elements of "newArray" using the loop.

In [100]:
for x in newArray:
    for elements in x:
        print(elements)

1
11
12
2
13
14
3
15
16


## Q#9: Reverse the columns and rows of "newArray".

In [101]:
revArray = np.flip(newArray)
print(revArray)

[[16 15  3]
 [14 13  2]
 [12 11  1]]


## Q#10: Decrement all elements of "newArray" with 1.

In [102]:
newArray -= 1
print(newArray)

[[ 0 10 11]
 [ 1 12 13]
 [ 2 14 15]]


## Q#11: Find smallest and biggest values in "newArray".

In [103]:
print(newArray.max())
print(newArray.min())

15
0


## Q#12: Print the first row of "newArray" using indexing.

In [104]:
print (newArray[0][0])

0


## Q#13: Print the number equals 12 of "newArray" using indexing.

In [105]:
print(newArray[1][1])

12


## Q#14: Print the numbers equal 0 and 13 of "newArray" using indexing.

In [106]:
print( newArray [0][0], newArray[1][2] )

0 13


## Q#15: Change the shape of "newArray" to (9,1).

In [107]:
newArray = np.reshape(newArray, (9, 1))
print(newArray)

[[ 0]
 [10]
 [11]
 [ 1]
 [12]
 [13]
 [ 2]
 [14]
 [15]]


## Q#16: Change the shape of "newArray" to (3,3).

In [108]:
newArray = np.reshape(newArray, (3, 3))
print(newArray)

[[ 0 10 11]
 [ 1 12 13]
 [ 2 14 15]]


# Well Done 🎉